### PR TITLE
No data found for this date range, symbol may be delisted

### PR DESCRIPTION
**Pull request by CHADHUB007**
main.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl['position'][aapl['Adj Close'] > aapl['SMA']] = 1
main.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aapl['position'][aapl['Adj Close'] < aapl['SMA']] = -1

### CODE REVIEW

**Comment by DESTHUbb** [comment]
To solve this problem, you can make a copy of the original DataFrame using the .copy() function before doing any value assignments. For example, instead of:

aapl = yf.download("AAPL")
aapl['position'][aapl['Adj Close'] > aapl['SMA']] = 1
aapl['position'][aapl['Adj Close'] < aapl['SMA']] = -1

**Comment by DESTHUbb** [comment]
AAPL data could not be downloaded for the specified date range. This may be because the symbol is no longer active on the market or because of problems with the internet connection.

**Comment by DESTHUbb** [comment]
To solve this problem, you can make a copy of the original DataFrame using the .copy() function before doing any value assignments. For example, instead of:

aapl = yf.download("AAPL")
aapl['position'][aapl['Adj Close'] > aapl['SMA']] = 1
aapl['position'][aapl['Adj Close'] < aapl['SMA']] = -1

**Comment by DESTHUbb** [comment]
The second error "SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame" is because you are trying to assign a value to a slice of a DataFrame, which can cause unwanted side effects or unexpected.

**Comment by DESTHUbb** [comment]
The second error "SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame" is because you are trying to assign a value to a slice of a DataFrame, which can cause unwanted side effects or unexpected. To fix this, you can use the Pandas "loc" method to assign values ​​to a copy of a DataFrame. For example, instead of writing:

aapl['position'][aapl['Adj Close'] > aapl['SMA']] = 1

It can be written:

aapl.loc[aapl['Adj Close'] > aapl['SMA'], 'position'] = 1

and instead of writing:

aapl['position'][aapl['Adj Close'] < aapl['SMA']] = -1

It can be written:

aapl.loc[aapl['Adj Close'] < aapl['SMA'], 'position'] = -1

**Comment by CHADHUB007** [comment]
Thanks for solving my second error

**Pull request merged**
